// src/permissions.js
export const PERMISSIONS = {
    // Administration
    ADMIN_VIEW: "Administration-Voir",
    STUDENT_ADD: "Administration-Gestion élève-Ajouter",
    STUDENT_DELETE: "Administration-Gestion élève-Supprimer",
    STUDENT_EDIT: "Administration-Gestion élève-Modifier",
    STUDENT_VIEW: "Administration-Gestion élève-Voir",
    PARENT_VIEW: "Administration-Gestion parents-Voir",
    PARENT_EDIT: "Administration-Gestion parents-Modifier",
    PARENT_DELETE: "Administration-Gestion parents-Supprimer",
    PARENT_ADD: "Administration-Gestion parents-Ajouter",
    TEACHER_ADD: "Administration-Gestion enseignant-Ajouter",
    TEACHER_EDIT: "Administration-Gestion enseignant-Modifier",
    TEACHER_VIEW: "Administration-Gestion enseignant-Voir",
    TEACHER_DELETE: "Administration-Gestion enseignant-Supprimer",
    PRIVILEGE_ADD: "Administration-Gestion privilège-Ajouter",
    PRIVILEGE_EDIT: "Administration-Gestion privilège-Modifier",
    PRIVILEGE_DELETE: "Administration-Gestion privilège-Supprimer",
    PRIVILEGE_VIEW: "Administration-Gestion privilège-Voir",
  
    // Académique
    ACADEMIC_VIEW: "Academique-Voir",
    TRIMESTER_ADD: "Academique-Trimestre-Ajouter",
    TRIMESTER_EDIT: "Academique-Trimestre-Modifier",
    TRIMESTER_DELETE: "Academique-Trimestre-Supprimer",
    TRIMESTER_VIEW: "Academique-Trimestre-Voir",
    CLASSROOM_VIEW: "Academique-Salle-Voir",
    CLASSROOM_DELETE: "Academique-Salle-Supprimer",
    CLASSROOM_EDIT: "Academique-Salle-Modifier",
    CLASSROOM_ADD: "Academique-Salle-Ajouter",
    LEVEL_ADD: "Academique-Niveaux-Ajouter",
    LEVEL_EDIT: "Academique-Niveaux-Modifier",
    LEVEL_DELETE: "Academique-Niveaux-Supprimer",
    LEVEL_VIEW: "Academique-Niveaux-Voir",
    SUBJECT_VIEW: "Academique-Matière-Voir",
    SUBJECT_DELETE: "Academique-Matière-Supprimer",
    SUBJECT_ADD: "Academique-Matière-Ajouter",
    SUBJECT_EDIT: "Academique-Matière-Modifier",
    SECTION_ADD: "Academique-Sections-Ajouter",
    SECTION_EDIT: "Academique-Sections-Modifier",
    SECTION_DELETE: "Academique-Sections-Supprimer",
    SECTION_VIEW: "Academique-Sections-Voir",
  
    // Ressources Humaines
    HR_VIEW: "Ressources Humaines-Voir",
    EMPLOYEE_ADD: "Ressources Humaines-Gestion des employées-Ajouter",
    EMPLOYEE_EDIT: "Ressources Humaines-Gestion des employées-Modifier",
    EMPLOYEE_DELETE: "Ressources Humaines-Gestion des employées-Supprimer",
    EMPLOYEE_VIEW: "Ressources Humaines-Gestion des employées-Voir",
    LEAVE_REQUEST_VIEW: "Ressources Humaines-Gestion demande de congé-Voir",
    LEAVE_REQUEST_DELETE: "Ressources Humaines-Gestion demande de congé-Supprimer",
    LEAVE_REQUEST_EDIT: "Ressources Humaines-Gestion demande de congé-Modifier",
    LEAVE_REQUEST_ADD: "Ressources Humaines-Gestion demande de congé-Ajouter",
    TIME_TRACKING_ADD: "Ressources Humaines-Gestion pointage-Ajouter",
    TIME_TRACKING_EDIT: "Ressources Humaines-Gestion pointage-Modifier",
    TIME_TRACKING_DELETE: "Ressources Humaines-Gestion pointage-Supprimer",
    TIME_TRACKING_VIEW: "Ressources Humaines-Gestion pointage-Voir",
    PAYROLL_VIEW: "Ressources Humaines-gestion de la paye-Voir",
    
    // Paramètres
    SETTINGS_VIEW: "Parametre-Voir",
    SCHOOL_ADD: "Parametre-Gestion écoles-Ajouter",
    SCHOOL_EDIT: "Parametre-Gestion écoles-Modifier",
    SCHOOL_DELETE: "Parametre-Gestion écoles-Supprimer",
    SCHOOL_VIEW: "Parametre-Gestion écoles-Voir"
  };