import React from 'react'

    export const nationalites = [
      { value: 'AF', label: 'Afghan' },
      { value: 'AL', label: 'Albanais' },
      { value: 'DZ', label: 'Algérien' },
      { value: 'AD', label: 'Andorran' },
      { value: 'AO', label: 'Angolais' },
      { value: 'AR', label: 'Argentin' },
      { value: 'AM', label: 'Arménien' },
      { value: 'AU', label: 'Australien' },
      { value: 'AT', label: 'Autrichien' },
      { value: 'AZ', label: 'Azerbaïdjanais' },
      { value: 'BS', label: 'Bahaméen' },
      { value: 'BH', label: 'Bahreïnien' },
      { value: 'BD', label: 'Bangladais' },
      { value: 'BY', label: 'Biélorusse' },
      { value: 'BE', label: 'Belge' },
      { value: 'BZ', label: 'Bélizien' },
      { value: 'BJ', label: 'Béninois' },
      { value: 'BT', label: 'Bhoutanais' },
      { value: 'BO', label: 'Bolivien' },
      { value: 'BA', label: 'Bosnien' },
      { value: 'BW', label: 'Botswana' },
      { value: 'BR', label: 'Brésilien' },
      { value: 'BN', label: 'Brunéien' },
      { value: 'BG', label: 'Bulgare' },
      { value: 'BF', label: 'Burkinabé' },
      { value: 'BI', label: 'Burundais' },
      { value: 'KH', label: 'Cambodgien' },
      { value: 'CM', label: 'Camerounais' },
      { value: 'CA', label: 'Canadien' },
      { value: 'CV', label: 'Cap-verdien' },
      { value: 'CF', label: 'Centrafricain' },
      { value: 'CL', label: 'Chilien' },
      { value: 'CN', label: 'Chinois' },
      { value: 'CO', label: 'Colombien' },
      { value: 'KM', label: 'Comorien' },
      { value: 'CG', label: 'Congolais' },
      { value: 'CR', label: 'Costaricien' },
      { value: 'HR', label: 'Croate' },
      { value: 'CU', label: 'Cubain' },
      { value: 'CY', label: 'Chypriote' },
      { value: 'CZ', label: 'Tchèque' },
      { value: 'CD', label: 'Congolais (RDC)' },
      { value: 'DK', label: 'Danois' },
      { value: 'DJ', label: 'Djiboutien' },
      { value: 'DM', label: 'Dominicain' },
      { value: 'DO', label: 'Dominicain (République)' },
      { value: 'EC', label: 'Équatorien' },
      { value: 'EG', label: 'Égyptien' },
      { value: 'SV', label: 'Salvadorien' },
      { value: 'GQ', label: 'Guinéen Équatoriale' },
      { value: 'ER', label: 'Érythréen' },
      { value: 'EE', label: 'Estonien' },
      { value: 'ET', label: 'Éthiopien' },
      { value: 'FJ', label: 'Fidjien' },
      { value: 'FI', label: 'Finlandais' },
      { value: 'FR', label: 'Français' },
      { value: 'GA', label: 'Gabonais' },
      { value: 'GM', label: 'Gambien' },
      { value: 'GE', label: 'Géorgien' },
      { value: 'DE', label: 'Allemand' },
      { value: 'GH', label: 'Ghanéen' },
      { value: 'GR', label: 'Grec' },
      { value: 'GD', label: 'Grenadien' },
      { value: 'GT', label: 'Guatémaltèque' },
      { value: 'GN', label: 'Guinéen' },
      { value: 'GW', label: 'Guinéen-Bissau' },
      { value: 'GY', label: 'Guyanien' },
      { value: 'HT', label: 'Haïtien' },
      { value: 'HN', label: 'Hondurien' },
      { value: 'HU', label: 'Hongrois' },
      { value: 'IS', label: 'Islandais' },
      { value: 'IN', label: 'Indien' },
      { value: 'ID', label: 'Indonésien' },
      { value: 'IR', label: 'Iranien' },
      { value: 'IQ', label: 'Irakien' },
      { value: 'IE', label: 'Irlandais' },
      { value: 'IL', label: 'Israélien' },
      { value: 'IT', label: 'Italien' },
      { value: 'JM', label: 'Jamaïcain' },
      { value: 'JP', label: 'Japonais' },
      { value: 'JO', label: 'Jordannien' },
      { value: 'KZ', label: 'Kazakh' },
      { value: 'KE', label: 'Kényan' },
      { value: 'KI', label: 'Kiribati' },
      { value: 'KW', label: 'Koweïtien' },
      { value: 'KG', label: 'Kirghiz' },
      { value: 'LA', label: 'Laotien' },
      { value: 'LV', label: 'Letton' },
      { value: 'LB', label: 'Libanais' },
      { value: 'LS', label: 'Lesothan' },
      { value: 'LR', label: 'Libérien' },
      { value: 'LY', label: 'Libyen' },
      { value: 'LT', label: 'Lituanien' },
      { value: 'LU', label: 'Luxembourgeois' },
      { value: 'MO', label: 'Macanais' },
      { value: 'MK', label: 'Macédonien' },
      { value: 'MG', label: 'Malagasy' },
      { value: 'MW', label: 'Malawien' },
      { value: 'MY', label: 'Malaisien' },
      { value: 'MV', label: 'Maldivien' },
      { value: 'ML', label: 'Malien' },
      { value: 'MT', label: 'Maltais' },
      { value: 'MH', label: 'Marshallais' },
      { value: 'MQ', label: 'Martiniquais' },
      { value: 'MR', label: 'Mauritanien' },
      { value: 'MU', label: 'Mauricien' },
      { value: 'YT', label: 'Mayennais' },
      { value: 'MX', label: 'Mexicain' },
      { value: 'FM', label: 'Micronésien' },
      { value: 'MD', label: 'Moldave' },
      { value: 'MC', label: 'Monégasque' },
      { value: 'MN', label: 'Mongol' },
      { value: 'ME', label: 'Monténégrin' },
      { value: 'MA', label: 'Marocain' },
      { value: 'MZ', label: 'Mozambicain' },
      { value: 'MM', label: 'Birman' },
      { value: 'NA', label: 'Namibien' },
      { value: 'NR', label: 'Nauruan' },
      { value: 'NP', label: 'Népalais' },
      { value: 'NL', label: 'Néerlandais' },
      { value: 'NC', label: 'Néo-Calédonien' },
      { value: 'NZ', label: 'Néo-Zélandais' },
      { value: 'NI', label: 'Nicaraguayen' },
      { value: 'NE', label: 'Nigerien' },
      { value: 'NG', label: 'Nigérian' },
      { value: 'NO', label: 'Norvégien' },
      { value: 'NP', label: 'Népalaise' },
      { value: 'OM', label: 'Omanais' },
      { value: 'PK', label: 'Pakistanais' },
      { value: 'PW', label: 'Palaosien' },
      { value: 'PA', label: 'Panaméen' },
      { value: 'PG', label: 'Papouasien (Nouvelle-Guinée)' },
      { value: 'PY', label: 'Paraguayen' },
      { value: 'PE', label: 'Péruvien' },
      { value: 'PH', label: 'Philippin' },
      { value: 'PL', label: 'Polonais' },
      { value: 'PT', label: 'Portugais' },
      { value: 'QA', label: 'Qatarien' },
      { value: 'RO', label: 'Roumain' },
      { value: 'RU', label: 'Russe' },
      { value: 'RW', label: 'Rwandais' },
      { value: 'ST', label: 'São-Toméen' },
      { value: 'SA', label: 'Saoudien' },
      { value: 'SN', label: 'Sénégalais' },
      { value: 'RS', label: 'Serbe' },
      { value: 'SC', label: 'Seychellois' },
      { value: 'SL', label: 'Sierra-Léonais' },
      { value: 'SG', label: 'Singapourien' },
      { value: 'SK', label: 'Slovaque' },
      { value: 'SI', label: 'Slovène' },
      { value: 'SB', label: 'Salomonais' },
      { value: 'SO', label: 'Somalien' },
      { value: 'ZA', label: 'Sud-Africain' },
      { value: 'ES', label: 'Espagnol' },
      { value: 'LK', label: 'Sri-Lankais' },
      { value: 'SD', label: 'Soudanais' },
      { value: 'SR', label: 'Surinamiens' },
      { value: 'SE', label: 'Suédois' },
      { value: 'CH', label: 'Suisse' },
      { value: 'SY', label: 'Syrien' },
      { value: 'TW', label: 'Taïwanais' },
      { value: 'TJ', label: 'Tadjik' },
      { value: 'TZ', label: 'Tanzanien' },
      { value: 'TH', label: 'Thaïlandais' },
      { value: 'TL', label: 'Timorais' },
      { value: 'TG', label: 'Togolais' },
      { value: 'TO', label: 'Tonga' },
      { value: 'TT', label: 'Trinidadien' },
      { value: 'TN', label: 'Tunisien' },
      { value: 'TR', label: 'Turc' },
      { value: 'TM', label: 'Turkmène' },
      { value: 'TV', label: 'Tuvaluan' },
      { value: 'UG', label: 'Ougandais' },
      { value: 'UA', label: 'Ukrainien' },
      { value: 'AE', label: 'Émirien' },
      { value: 'GB', label: 'Britannique' },
      { value: 'US', label: 'Américain' },
      { value: 'UY', label: 'Uruguayen' },
      { value: 'UZ', label: 'Ouzbek' },
      { value: 'VU', label: 'Vanuatais' },
      { value: 'VA', label: 'Vaticanais' },
      { value: 'VE', label: 'Vénézuélien' },
      { value: 'VN', label: 'Vietnamien' },
      { value: 'YE', label: 'Yéménite' },
      { value: 'ZM', label: 'Zambien' },
      { value: 'ZW', label: 'Zimbabwéen' }
    ];

    export const Paiement = [
      { value: 'virement bancaire', label: 'virement bancaire' },
      { value: 'ccp', label: 'ccp' },
      { value: 'paiement en espéces', label: 'paiement en espéces' }
    ];
    
   
    export const StatutPointage=[
      {value: 'present', label: 'Présent' },
      {value: 'retard', label: 'En retard' },
      {value: 'absent', label: 'Absent' },
    ]
 
    export const pays = [
      { value: 'AF', label: 'Afghanistan' },
      { value: 'AL', label: 'Albanie' },
      { value: 'DZ', label: 'Algérie' },
      { value: 'AD', label: 'Andorre' },
      { value: 'AO', label: 'Angola' },
      { value: 'AR', label: 'Argentine' },
      { value: 'AM', label: 'Arménie' },
      { value: 'AU', label: 'Australie' },
      { value: 'AT', label: 'Autriche' },
      { value: 'AZ', label: 'Azerbaïdjan' },
      { value: 'BS', label: 'Bahamas' },
      { value: 'BH', label: 'Bahreïn' },
      { value: 'BD', label: 'Bangladesh' },
      { value: 'BB', label: 'Barbade' },
      { value: 'BY', label: 'Biélorussie' },
      { value: 'BE', label: 'Belgique' },
      { value: 'BZ', label: 'Belize' },
      { value: 'BJ', label: 'Bénin' },
      { value: 'BT', label: 'Bhoutan' },
      { value: 'BO', label: 'Bolivie' },
      { value: 'BA', label: 'Bosnie-Herzégovine' },
      { value: 'BW', label: 'Botswana' },
      { value: 'BR', label: 'Brésil' },
      { value: 'BN', label: 'Brunei' },
      { value: 'BG', label: 'Bulgarie' },
      { value: 'BF', label: 'Burkina Faso' },
      { value: 'BI', label: 'Burundi' },
      { value: 'KH', label: 'Cambodge' },
      { value: 'CM', label: 'Cameroun' },
      { value: 'CA', label: 'Canada' },
      { value: 'CV', label: 'Cap-Vert' },
      { value: 'CF', label: 'République centrafricaine' },
      { value: 'TD', label: 'Tchad' },
      { value: 'CL', label: 'Chili' },
      { value: 'CN', label: 'Chine' },
      { value: 'CO', label: 'Colombie' },
      { value: 'KM', label: 'Comores' },
      { value: 'CG', label: 'Congo' },
      { value: 'CR', label: 'Costa Rica' },
      { value: 'HR', label: 'Croatie' },
      { value: 'CU', label: 'Cuba' },
      { value: 'CY', label: 'Chypre' },
      { value: 'CZ', label: 'République tchèque' },
      { value: 'DK', label: 'Danemark' },
      { value: 'DJ', label: 'Djibouti' },
      { value: 'DM', label: 'Dominique' },
      { value: 'DO', label: 'République dominicaine' },
      { value: 'EC', label: 'Équateur' },
      { value: 'EG', label: 'Égypte' },
      { value: 'SV', label: 'El Salvador' },
      { value: 'GQ', label: 'Guinée équatoriale' },
      { value: 'ER', label: 'Érythrée' },
      { value: 'EE', label: 'Estonie' },
      { value: 'ET', label: 'Éthiopie' },
      { value: 'FI', label: 'Finlande' },
      { value: 'FR', label: 'France' },
      { value: 'GA', label: 'Gabon' },
      { value: 'GM', label: 'Gambie' },
      { value: 'GE', label: 'Géorgie' },
      { value: 'DE', label: 'Allemagne' },
      { value: 'GH', label: 'Ghana' },
      { value: 'GR', label: 'Grèce' },
      { value: 'GT', label: 'Guatemala' },
      { value: 'GN', label: 'Guinée' },
      { value: 'GW', label: 'Guinée-Bissau' },
      { value: 'HT', label: 'Haïti' },
      { value: 'HN', label: 'Honduras' },
      { value: 'HU', label: 'Hongrie' },
      { value: 'IS', label: 'Islande' },
      { value: 'IN', label: 'Inde' },
      { value: 'ID', label: 'Indonésie' },
      { value: 'IR', label: 'Iran' },
      { value: 'IQ', label: 'Irak' },
      { value: 'IE', label: 'Irlande' },
      { value: 'IT', label: 'Italie' },
      { value: 'JM', label: 'Jamaïque' },
      { value: 'JP', label: 'Japon' },
      { value: 'JO', label: 'Jordanie' },
      { value: 'KZ', label: 'Kazakhstan' },
      { value: 'KE', label: 'Kenya' },
      { value: 'KW', label: 'Koweït' },
      { value: 'LA', label: 'Laos' },
      { value: 'LV', label: 'Lettonie' },
      { value: 'LB', label: 'Liban' },
      { value: 'LS', label: 'Lesotho' },
      { value: 'LR', label: 'Libéria' },
      { value: 'LY', label: 'Libye' },
      { value: 'LT', label: 'Lituanie' },
      { value: 'LU', label: 'Luxembourg' },
      { value: 'MG', label: 'Madagascar' },
      { value: 'MW', label: 'Malawi' },
      { value: 'MY', label: 'Malaisie' },
      { value: 'MV', label: 'Maldives' },
      { value: 'ML', label: 'Mali' },
      { value: 'MT', label: 'Malte' },
      { value: 'MX', label: 'Mexique' },
      { value: 'MA', label: 'Maroc' },
      { value: 'MZ', label: 'Mozambique' },
      { value: 'NA', label: 'Namibie' },
      { value: 'NP', label: 'Népal' },
      { value: 'NL', label: 'Pays-Bas' },
      { value: 'NZ', label: 'Nouvelle-Zélande' },
      { value: 'NI', label: 'Nicaragua' },
      { value: 'NG', label: 'Nigéria' },
      { value: 'NO', label: 'Norvège' },
      { value: 'OM', label: 'Oman' },
      { value: 'PK', label: 'Pakistan' },
      { value: 'PA', label: 'Panama' },
      { value: 'PY', label: 'Paraguay' },
      { value: 'PE', label: 'Pérou' },
      { value: 'PH', label: 'Philippines' },
      { value: 'PL', label: 'Pologne' },
      { value: 'PT', label: 'Portugal' },
      { value: 'QA', label: 'Qatar' },
      { value: 'RO', label: 'Roumanie' },
      { value: 'RU', label: 'Russie' },
      { value: 'SA', label: 'Arabie Saoudite' },
      { value: 'SN', label: 'Sénégal' },
      { value: 'RS', label: 'Serbie' },
      { value: 'SG', label: 'Singapour' },
      { value: 'ES', label: 'Espagne' },
      { value: 'SE', label: 'Suède' },
      { value: 'CH', label: 'Suisse' },
      { value: 'TH', label: 'Thaïlande' },
      { value: 'TN', label: 'Tunisie' },
      { value: 'TR', label: 'Turquie' },
      { value: 'UA', label: 'Ukraine' },
      { value: 'GB', label: 'Royaume-Uni' },
      { value: 'US', label: 'États-Unis' },
      { value: 'VN', label: 'Viêt Nam' }
    ];
    
    